name: mobile_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  file_picker: ^8.1.4
  permission_handler: ^11.3.1
  flutter_native_splash: ^2.4.3
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  dio: ^5.7.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  hive_generator: ^2.0.1
  timeago: ^3.7.0
  http_parser: ^4.0.2
  injectable: ^2.5.0
  get_it: ^8.0.2
  easy_localization: ^3.0.7
  dfunc: ^0.10.0
  auto_route: ^9.2.2
  fluttertoast: ^8.2.8
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  retrofit_generator: ^9.1.5
  json_serializable: ^6.9.0
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
  auto_route_generator: ^9.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
  # font:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Light.ttf
  #         weight: 300
  #       - asset: assets/fonts/Inter-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Light.ttf
  #         weight: 300
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Light.ttf
  #         weight: 300
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700

flutter_gen:
  output: lib/generated/
  line_length: 80

  integrations:
    flutter_svg: true
